about_widget_content = "Lorem ipsum dolor sit amet, conse tfctetur adipiscing elit. Vel in in donec iaculis tempasus odio nunc laoreet . Libero ullam rgscorper."
address = "West Java, Indonesia"
author = "Rhymeus"
categories_title = "Blog Categories"
contact_form_action = "mail:rhymebounty@gmail.com"
copyright = "Copyright by Rhymeus"
custom_script = ""
description = "This is meta description"
email = "rhymebounty@gmail.com"
error_404_button = "Back To Home"
error_404_text = "404 Page Not Found!"
favicon = "images/favicon.png"
featured_post_button = "Featured"
featured_post_title = "Featured Post"
footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Writeups"
logo_width = "150x"
mainSections = ["blog"]
mobile = "-"
navbar_fixed = false
next_button = "Next"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"
posts_title = "Featured"
previous_button = "Previous"
read_more_button = "Read more"
recent_post_button = "Recent"
recent_post_title = "Recent Post"
related_posts = "Related Posts"
search = true
showing_posts = "Showing Post From"
theme_copyright = false
[advertisement]
image = "images/promotion.png"
link = "../"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Know About Me"
button_link = "about/"
content = "Undergraduate Information System at University of Singaperbangsa, who have passioned in Cyber Security, Penetration Testing, Front-end Web Development. i have an experience in Bug hunting."
enable = true
image = "images/banner.png"
title_large = "Welcome **!**"
title_small = "to Rhymeus Blog"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = true
preloader = "Rhymeus"
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
newsletter_button = "Sign in"
newsletter_invitation = "Subscribe to this blog to get our best writeups submitted every week!"
newsletter_placeholder = "Type And Hit Enter"
newsletter_reminder_a = "By Singing Up, You Agree To"
newsletter_reminder_b = "Privacy Policy"
newsletter_title = "Newsletter"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/rhymeus_"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/raysepta_"
title = "instagram"
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/ahmadray/"
title = "linkedin"
